/* tslint:disable */
/* eslint-disable */
/**
 * Push Notification API
 * API for managing push notifications and campaigns
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Campaign
 */
export interface Campaign {
    /**
     * Unique identifier for the campaign
     * @type {string}
     * @memberof Campaign
     */
    '_id': string;
    /**
     * Name of the campaign
     * @type {string}
     * @memberof Campaign
     */
    'name': string;
    /**
     * Tags associated with the campaign
     * @type {Array<string>}
     * @memberof Campaign
     */
    'tags'?: Array<string>;
    /**
     * Title of the notifications
     * @type {string}
     * @memberof Campaign
     */
    'title': string;
    /**
     * Body text of the notifications
     * @type {string}
     * @memberof Campaign
     */
    'body': string;
    /**
     * URL to open when the notification is clicked
     * @type {string}
     * @memberof Campaign
     */
    'click_url'?: string;
    /**
     * Scheduled time for the campaign
     * @type {string}
     * @memberof Campaign
     */
    'schedule_at'?: string;
    /**
     * Status of the campaign
     * @type {string}
     * @memberof Campaign
     */
    'status'?: CampaignStatusEnum;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof Campaign
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof Campaign
     */
    'updated_at'?: string;
}

export const CampaignStatusEnum = {
    New: 'new',
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type CampaignStatusEnum = typeof CampaignStatusEnum[keyof typeof CampaignStatusEnum];

/**
 * Paginated list of campaigns
 * @export
 * @interface CampaignsGet200Response
 */
export interface CampaignsGet200Response {
    /**
     * Total number of campaigns
     * @type {number}
     * @memberof CampaignsGet200Response
     */
    'total'?: number;
    /**
     * Number of campaigns returned
     * @type {number}
     * @memberof CampaignsGet200Response
     */
    'limit'?: number;
    /**
     * Offset for pagination
     * @type {number}
     * @memberof CampaignsGet200Response
     */
    'offset'?: number;
    /**
     * List of campaigns
     * @type {Array<CampaignsGet200ResponseItemsInner>}
     * @memberof CampaignsGet200Response
     */
    'items'?: Array<CampaignsGet200ResponseItemsInner>;
}
/**
 * 
 * @export
 * @interface CampaignsGet200ResponseItemsInner
 */
export interface CampaignsGet200ResponseItemsInner {
    /**
     * Unique identifier for the campaign
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    '_id': string;
    /**
     * Name of the campaign
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'name': string;
    /**
     * Tags associated with the campaign
     * @type {Array<string>}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'tags'?: Array<string>;
    /**
     * Title of the notifications
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'title': string;
    /**
     * Body text of the notifications
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'body': string;
    /**
     * URL to open when the notification is clicked
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'click_url'?: string;
    /**
     * Scheduled time for the campaign
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'schedule_at'?: string;
    /**
     * Status of the campaign
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'status'?: CampaignsGet200ResponseItemsInnerStatusEnum;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof CampaignsGet200ResponseItemsInner
     */
    'updated_at'?: string;
}

export const CampaignsGet200ResponseItemsInnerStatusEnum = {
    New: 'new',
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type CampaignsGet200ResponseItemsInnerStatusEnum = typeof CampaignsGet200ResponseItemsInnerStatusEnum[keyof typeof CampaignsGet200ResponseItemsInnerStatusEnum];

/**
 * Bad Request
 * @export
 * @interface CampaignsGet400Response
 */
export interface CampaignsGet400Response {
    /**
     * Error message indicating the request was invalid
     * @type {string}
     * @memberof CampaignsGet400Response
     */
    'message'?: string;
    /**
     * 
     * @type {Array<CampaignsGet400ResponseErrorsInner>}
     * @memberof CampaignsGet400Response
     */
    'errors'?: Array<CampaignsGet400ResponseErrorsInner>;
}
/**
 * 
 * @export
 * @interface CampaignsGet400ResponseErrorsInner
 */
export interface CampaignsGet400ResponseErrorsInner {
    /**
     * The field that caused the error
     * @type {string}
     * @memberof CampaignsGet400ResponseErrorsInner
     */
    'field': string;
    /**
     * Error message for the field
     * @type {string}
     * @memberof CampaignsGet400ResponseErrorsInner
     */
    'message': string;
}
/**
 * Unauthorized
 * @export
 * @interface CampaignsGet401Response
 */
export interface CampaignsGet401Response {
    /**
     * Error message indicating the request is unauthorized
     * @type {string}
     * @memberof CampaignsGet401Response
     */
    'message'?: string;
}
/**
 * Not Found
 * @export
 * @interface CampaignsIdGet404Response
 */
export interface CampaignsIdGet404Response {
    /**
     * Error message indicating the resource was not found
     * @type {string}
     * @memberof CampaignsIdGet404Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface CampaignsPostRequest
 */
export interface CampaignsPostRequest {
    /**
     * Name of the campaign
     * @type {string}
     * @memberof CampaignsPostRequest
     */
    'name': string;
    /**
     * Tags associated with the campaign
     * @type {Array<string>}
     * @memberof CampaignsPostRequest
     */
    'tags'?: Array<string>;
    /**
     * Title of the notifications
     * @type {string}
     * @memberof CampaignsPostRequest
     */
    'title': string;
    /**
     * Body text of the notifications
     * @type {string}
     * @memberof CampaignsPostRequest
     */
    'body': string;
    /**
     * URL to open when the notification is clicked
     * @type {string}
     * @memberof CampaignsPostRequest
     */
    'click_url'?: string;
}
/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * Unique identifier for the device
     * @type {string}
     * @memberof Device
     */
    '_id': string;
    /**
     * Unique device token
     * @type {string}
     * @memberof Device
     */
    'device_token': string;
    /**
     * Platform of the device
     * @type {string}
     * @memberof Device
     */
    'platform': DevicePlatformEnum;
    /**
     * User identifier
     * @type {string}
     * @memberof Device
     */
    'user_id'?: string;
    /**
     * User email
     * @type {string}
     * @memberof Device
     */
    'email'?: string;
    /**
     * Tags associated with the device
     * @type {Array<string>}
     * @memberof Device
     */
    'tags'?: Array<string>;
    /**
     * Indicates if the device has undelivered notifications
     * @type {boolean}
     * @memberof Device
     */
    'undelivered'?: boolean;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof Device
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof Device
     */
    'updated_at'?: string;
}

export const DevicePlatformEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web'
} as const;

export type DevicePlatformEnum = typeof DevicePlatformEnum[keyof typeof DevicePlatformEnum];

/**
 * Paginated list of devices
 * @export
 * @interface DevicesGet200Response
 */
export interface DevicesGet200Response {
    /**
     * Total number of devices
     * @type {number}
     * @memberof DevicesGet200Response
     */
    'total'?: number;
    /**
     * Number of devices returned
     * @type {number}
     * @memberof DevicesGet200Response
     */
    'limit'?: number;
    /**
     * Offset for pagination
     * @type {number}
     * @memberof DevicesGet200Response
     */
    'offset'?: number;
    /**
     * List of devices
     * @type {Array<DevicesGet200ResponseItemsInner>}
     * @memberof DevicesGet200Response
     */
    'items'?: Array<DevicesGet200ResponseItemsInner>;
}
/**
 * 
 * @export
 * @interface DevicesGet200ResponseItemsInner
 */
export interface DevicesGet200ResponseItemsInner {
    /**
     * Unique identifier for the device
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    '_id': string;
    /**
     * Unique device token
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'device_token': string;
    /**
     * Platform of the device
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'platform': DevicesGet200ResponseItemsInnerPlatformEnum;
    /**
     * User identifier
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'user_id'?: string;
    /**
     * User email
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'email'?: string;
    /**
     * Tags associated with the device
     * @type {Array<string>}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'tags'?: Array<string>;
    /**
     * Indicates if the device has undelivered notifications
     * @type {boolean}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'undelivered'?: boolean;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof DevicesGet200ResponseItemsInner
     */
    'updated_at'?: string;
}

export const DevicesGet200ResponseItemsInnerPlatformEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web'
} as const;

export type DevicesGet200ResponseItemsInnerPlatformEnum = typeof DevicesGet200ResponseItemsInnerPlatformEnum[keyof typeof DevicesGet200ResponseItemsInnerPlatformEnum];

/**
 * 
 * @export
 * @interface DevicesPostRequest
 */
export interface DevicesPostRequest {
    /**
     * Unique device token
     * @type {string}
     * @memberof DevicesPostRequest
     */
    'device_token': string;
    /**
     * Platform of the device
     * @type {string}
     * @memberof DevicesPostRequest
     */
    'platform': DevicesPostRequestPlatformEnum;
    /**
     * User identifier
     * @type {string}
     * @memberof DevicesPostRequest
     */
    'user_id'?: string;
    /**
     * User email
     * @type {string}
     * @memberof DevicesPostRequest
     */
    'email'?: string;
    /**
     * Tags associated with the device
     * @type {Array<string>}
     * @memberof DevicesPostRequest
     */
    'tags'?: Array<string>;
}

export const DevicesPostRequestPlatformEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web'
} as const;

export type DevicesPostRequestPlatformEnum = typeof DevicesPostRequestPlatformEnum[keyof typeof DevicesPostRequestPlatformEnum];

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * Unique identifier for the notification
     * @type {string}
     * @memberof Notification
     */
    '_id': string;
    /**
     * Identifier of the device to which the notification was sent
     * @type {string}
     * @memberof Notification
     */
    'device_id': string;
    /**
     * Identifier of the campaign associated with the notification
     * @type {string}
     * @memberof Notification
     */
    'campaign_id': string;
    /**
     * Title of the notification
     * @type {string}
     * @memberof Notification
     */
    'title': string;
    /**
     * Body text of the notification
     * @type {string}
     * @memberof Notification
     */
    'body': string;
    /**
     * URL to open when the notification is clicked
     * @type {string}
     * @memberof Notification
     */
    'click_url'?: string;
    /**
     * Status of the notification
     * @type {string}
     * @memberof Notification
     */
    'status': NotificationStatusEnum;
    /**
     * Number of attempts made to send the notification
     * @type {number}
     * @memberof Notification
     */
    'attempt'?: number;
    /**
     * Timestamp for the next attempt to send the notification
     * @type {string}
     * @memberof Notification
     */
    'next_attempt'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof Notification
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof Notification
     */
    'updated_at'?: string;
}

export const NotificationStatusEnum = {
    New: 'new',
    Sent: 'sent',
    Failed: 'failed',
    Delivered: 'delivered',
    Undelivered: 'undelivered'
} as const;

export type NotificationStatusEnum = typeof NotificationStatusEnum[keyof typeof NotificationStatusEnum];

/**
 * Paginated list of notifications
 * @export
 * @interface NotificationsGet200Response
 */
export interface NotificationsGet200Response {
    /**
     * Total number of notifications
     * @type {number}
     * @memberof NotificationsGet200Response
     */
    'total'?: number;
    /**
     * Number of notifications returned
     * @type {number}
     * @memberof NotificationsGet200Response
     */
    'limit'?: number;
    /**
     * Offset for pagination
     * @type {number}
     * @memberof NotificationsGet200Response
     */
    'offset'?: number;
    /**
     * List of notifications
     * @type {Array<NotificationsGet200ResponseItemsInner>}
     * @memberof NotificationsGet200Response
     */
    'items'?: Array<NotificationsGet200ResponseItemsInner>;
}
/**
 * 
 * @export
 * @interface NotificationsGet200ResponseItemsInner
 */
export interface NotificationsGet200ResponseItemsInner {
    /**
     * Unique identifier for the notification
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    '_id': string;
    /**
     * Identifier of the device to which the notification was sent
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'device_id': string;
    /**
     * Identifier of the campaign associated with the notification
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'campaign_id': string;
    /**
     * Title of the notification
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'title': string;
    /**
     * Body text of the notification
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'body': string;
    /**
     * URL to open when the notification is clicked
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'click_url'?: string;
    /**
     * Status of the notification
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'status': NotificationsGet200ResponseItemsInnerStatusEnum;
    /**
     * Number of attempts made to send the notification
     * @type {number}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'attempt'?: number;
    /**
     * Timestamp for the next attempt to send the notification
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'next_attempt'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof NotificationsGet200ResponseItemsInner
     */
    'updated_at'?: string;
}

export const NotificationsGet200ResponseItemsInnerStatusEnum = {
    New: 'new',
    Sent: 'sent',
    Failed: 'failed',
    Delivered: 'delivered',
    Undelivered: 'undelivered'
} as const;

export type NotificationsGet200ResponseItemsInnerStatusEnum = typeof NotificationsGet200ResponseItemsInnerStatusEnum[keyof typeof NotificationsGet200ResponseItemsInnerStatusEnum];


/**
 * CampaignsApi - axios parameter creator
 * @export
 */
export const CampaignsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a list of campaigns with optional filters
         * @summary Get list of campaigns
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {Array<string>} [tags] Tags to filter campaigns
         * @param {string} [name] Name to filter campaigns
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsGet: async (limit?: number, offset?: number, tags?: Array<string>, name?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/campaigns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Clone a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdClonePost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('campaignsIdClonePost', 'id', id)
            const localVarPath = `/campaigns/{_id}/clone`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('campaignsIdDelete', 'id', id)
            const localVarPath = `/campaigns/{_id}`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a campaign by ID
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('campaignsIdGet', 'id', id)
            const localVarPath = `/campaigns/{_id}`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a campaign
         * @param {string} id Unique identifier
         * @param {CampaignsPostRequest} campaignsPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdPut: async (id: string, campaignsPostRequest: CampaignsPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('campaignsIdPut', 'id', id)
            // verify required parameter 'campaignsPostRequest' is not null or undefined
            assertParamExists('campaignsIdPut', 'campaignsPostRequest', campaignsPostRequest)
            const localVarPath = `/campaigns/{_id}`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(campaignsPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Run a campaign immediately or schedule it for later execution
         * @summary Run a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdRunPost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('campaignsIdRunPost', 'id', id)
            const localVarPath = `/campaigns/{_id}/run`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a campaign
         * @param {CampaignsPostRequest} campaignsPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsPost: async (campaignsPostRequest: CampaignsPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campaignsPostRequest' is not null or undefined
            assertParamExists('campaignsPost', 'campaignsPostRequest', campaignsPostRequest)
            const localVarPath = `/campaigns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(campaignsPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CampaignsApi - functional programming interface
 * @export
 */
export const CampaignsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CampaignsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a list of campaigns with optional filters
         * @summary Get list of campaigns
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {Array<string>} [tags] Tags to filter campaigns
         * @param {string} [name] Name to filter campaigns
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsGet(limit?: number, offset?: number, tags?: Array<string>, name?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsGet(limit, offset, tags, name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Clone a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsIdClonePost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignsGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsIdClonePost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsIdClonePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a campaign by ID
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignsGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a campaign
         * @param {string} id Unique identifier
         * @param {CampaignsPostRequest} campaignsPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsIdPut(id: string, campaignsPostRequest: CampaignsPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignsGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsIdPut(id, campaignsPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Run a campaign immediately or schedule it for later execution
         * @summary Run a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsIdRunPost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignsGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsIdRunPost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsIdRunPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a campaign
         * @param {CampaignsPostRequest} campaignsPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async campaignsPost(campaignsPostRequest: CampaignsPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignsGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.campaignsPost(campaignsPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignsApi.campaignsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CampaignsApi - factory interface
 * @export
 */
export const CampaignsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CampaignsApiFp(configuration)
    return {
        /**
         * Get a list of campaigns with optional filters
         * @summary Get list of campaigns
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {Array<string>} [tags] Tags to filter campaigns
         * @param {string} [name] Name to filter campaigns
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsGet(limit?: number, offset?: number, tags?: Array<string>, name?: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignsGet200Response> {
            return localVarFp.campaignsGet(limit, offset, tags, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Clone a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdClonePost(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignsGet200ResponseItemsInner> {
            return localVarFp.campaignsIdClonePost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.campaignsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a campaign by ID
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignsGet200ResponseItemsInner> {
            return localVarFp.campaignsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a campaign
         * @param {string} id Unique identifier
         * @param {CampaignsPostRequest} campaignsPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdPut(id: string, campaignsPostRequest: CampaignsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CampaignsGet200ResponseItemsInner> {
            return localVarFp.campaignsIdPut(id, campaignsPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Run a campaign immediately or schedule it for later execution
         * @summary Run a campaign
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsIdRunPost(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CampaignsGet200ResponseItemsInner> {
            return localVarFp.campaignsIdRunPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a campaign
         * @param {CampaignsPostRequest} campaignsPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        campaignsPost(campaignsPostRequest: CampaignsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CampaignsGet200ResponseItemsInner> {
            return localVarFp.campaignsPost(campaignsPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CampaignsApi - object-oriented interface
 * @export
 * @class CampaignsApi
 * @extends {BaseAPI}
 */
export class CampaignsApi extends BaseAPI {
    /**
     * Get a list of campaigns with optional filters
     * @summary Get list of campaigns
     * @param {number} [limit] Maximum number of items to return
     * @param {number} [offset] Number of items to skip before starting to collect the result set
     * @param {Array<string>} [tags] Tags to filter campaigns
     * @param {string} [name] Name to filter campaigns
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsGet(limit?: number, offset?: number, tags?: Array<string>, name?: string, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsGet(limit, offset, tags, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Clone a campaign
     * @param {string} id Unique identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsIdClonePost(id: string, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsIdClonePost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a campaign
     * @param {string} id Unique identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a campaign by ID
     * @param {string} id Unique identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a campaign
     * @param {string} id Unique identifier
     * @param {CampaignsPostRequest} campaignsPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsIdPut(id: string, campaignsPostRequest: CampaignsPostRequest, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsIdPut(id, campaignsPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Run a campaign immediately or schedule it for later execution
     * @summary Run a campaign
     * @param {string} id Unique identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsIdRunPost(id: string, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsIdRunPost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a campaign
     * @param {CampaignsPostRequest} campaignsPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    public campaignsPost(campaignsPostRequest: CampaignsPostRequest, options?: RawAxiosRequestConfig) {
        return CampaignsApiFp(this.configuration).campaignsPost(campaignsPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DevicesApi - axios parameter creator
 * @export
 */
export const DevicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Name to filter entities
         * @summary Get list of devices with filters
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {Array<string>} [tags] Tags to filter entities
         * @param {string} [email] Email to filter entities
         * @param {string} [deviceToken] Device token to filter entities
         * @param {DevicesGetPlatformEnum} [platform] Platform to filter entities
         * @param {string} [userId] User ID to filter entities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesGet: async (limit?: number, offset?: number, tags?: Array<string>, email?: string, deviceToken?: string, platform?: DevicesGetPlatformEnum, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (deviceToken !== undefined) {
                localVarQueryParameter['device_token'] = deviceToken;
            }

            if (platform !== undefined) {
                localVarQueryParameter['platform'] = platform;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a device
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('devicesIdDelete', 'id', id)
            const localVarPath = `/devices/{_id}`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a device by ID
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('devicesIdGet', 'id', id)
            const localVarPath = `/devices/{_id}`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a device
         * @param {string} id Unique identifier
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesIdPut: async (id: string, devicesPostRequest: DevicesPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('devicesIdPut', 'id', id)
            // verify required parameter 'devicesPostRequest' is not null or undefined
            assertParamExists('devicesIdPut', 'devicesPostRequest', devicesPostRequest)
            const localVarPath = `/devices/{_id}`
                .replace(`{${"_id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(devicesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Import devices from a CSV file. The file should contain device tokens, platforms, and optional user IDs and tags. Example CSV format: ``` device_token,platform,user_id,tags token1,ios,user1,tag1 token2,android,user2,\"tag2,tag3\" ```
         * @summary Import devices via CSV file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesImportPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/devices/import`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a device
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesPost: async (devicesPostRequest: DevicesPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'devicesPostRequest' is not null or undefined
            assertParamExists('devicesPost', 'devicesPostRequest', devicesPostRequest)
            const localVarPath = `/devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(devicesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DevicesApi - functional programming interface
 * @export
 */
export const DevicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DevicesApiAxiosParamCreator(configuration)
    return {
        /**
         * Name to filter entities
         * @summary Get list of devices with filters
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {Array<string>} [tags] Tags to filter entities
         * @param {string} [email] Email to filter entities
         * @param {string} [deviceToken] Device token to filter entities
         * @param {DevicesGetPlatformEnum} [platform] Platform to filter entities
         * @param {string} [userId] User ID to filter entities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesGet(limit?: number, offset?: number, tags?: Array<string>, email?: string, deviceToken?: string, platform?: DevicesGetPlatformEnum, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DevicesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesGet(limit, offset, tags, email, deviceToken, platform, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.devicesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a device
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.devicesIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a device by ID
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DevicesGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.devicesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a device
         * @param {string} id Unique identifier
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesIdPut(id: string, devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DevicesGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesIdPut(id, devicesPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.devicesIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Import devices from a CSV file. The file should contain device tokens, platforms, and optional user IDs and tags. Example CSV format: ``` device_token,platform,user_id,tags token1,ios,user1,tag1 token2,android,user2,\"tag2,tag3\" ```
         * @summary Import devices via CSV file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesImportPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesImportPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.devicesImportPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a device
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesPost(devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DevicesGet200ResponseItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesPost(devicesPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevicesApi.devicesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DevicesApi - factory interface
 * @export
 */
export const DevicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DevicesApiFp(configuration)
    return {
        /**
         * Name to filter entities
         * @summary Get list of devices with filters
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {Array<string>} [tags] Tags to filter entities
         * @param {string} [email] Email to filter entities
         * @param {string} [deviceToken] Device token to filter entities
         * @param {DevicesGetPlatformEnum} [platform] Platform to filter entities
         * @param {string} [userId] User ID to filter entities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesGet(limit?: number, offset?: number, tags?: Array<string>, email?: string, deviceToken?: string, platform?: DevicesGetPlatformEnum, userId?: string, options?: RawAxiosRequestConfig): AxiosPromise<DevicesGet200Response> {
            return localVarFp.devicesGet(limit, offset, tags, email, deviceToken, platform, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a device
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.devicesIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a device by ID
         * @param {string} id Unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<DevicesGet200ResponseItemsInner> {
            return localVarFp.devicesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a device
         * @param {string} id Unique identifier
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesIdPut(id: string, devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<DevicesGet200ResponseItemsInner> {
            return localVarFp.devicesIdPut(id, devicesPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Import devices from a CSV file. The file should contain device tokens, platforms, and optional user IDs and tags. Example CSV format: ``` device_token,platform,user_id,tags token1,ios,user1,tag1 token2,android,user2,\"tag2,tag3\" ```
         * @summary Import devices via CSV file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesImportPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.devicesImportPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a device
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesPost(devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<DevicesGet200ResponseItemsInner> {
            return localVarFp.devicesPost(devicesPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DevicesApi - object-oriented interface
 * @export
 * @class DevicesApi
 * @extends {BaseAPI}
 */
export class DevicesApi extends BaseAPI {
    /**
     * Name to filter entities
     * @summary Get list of devices with filters
     * @param {number} [limit] Maximum number of items to return
     * @param {number} [offset] Number of items to skip before starting to collect the result set
     * @param {Array<string>} [tags] Tags to filter entities
     * @param {string} [email] Email to filter entities
     * @param {string} [deviceToken] Device token to filter entities
     * @param {DevicesGetPlatformEnum} [platform] Platform to filter entities
     * @param {string} [userId] User ID to filter entities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public devicesGet(limit?: number, offset?: number, tags?: Array<string>, email?: string, deviceToken?: string, platform?: DevicesGetPlatformEnum, userId?: string, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).devicesGet(limit, offset, tags, email, deviceToken, platform, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a device
     * @param {string} id Unique identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public devicesIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).devicesIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a device by ID
     * @param {string} id Unique identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public devicesIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).devicesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a device
     * @param {string} id Unique identifier
     * @param {DevicesPostRequest} devicesPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public devicesIdPut(id: string, devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).devicesIdPut(id, devicesPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Import devices from a CSV file. The file should contain device tokens, platforms, and optional user IDs and tags. Example CSV format: ``` device_token,platform,user_id,tags token1,ios,user1,tag1 token2,android,user2,\"tag2,tag3\" ```
     * @summary Import devices via CSV file
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public devicesImportPost(options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).devicesImportPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a device
     * @param {DevicesPostRequest} devicesPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DevicesApi
     */
    public devicesPost(devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig) {
        return DevicesApiFp(this.configuration).devicesPost(devicesPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const DevicesGetPlatformEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web'
} as const;
export type DevicesGetPlatformEnum = typeof DevicesGetPlatformEnum[keyof typeof DevicesGetPlatformEnum];


/**
 * NotificationsApi - axios parameter creator
 * @export
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get list of notifications
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {string} [campaignId] Filter notifications by campaign ID
         * @param {NotificationsGetStatusEnum} [status] Filter notifications by status
         * @param {string} [deviceId] Filter notifications by device ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsGet: async (limit?: number, offset?: number, campaignId?: string, status?: NotificationsGetStatusEnum, deviceId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (campaignId !== undefined) {
                localVarQueryParameter['campaign_id'] = campaignId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (deviceId !== undefined) {
                localVarQueryParameter['device_id'] = deviceId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 * @export
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get list of notifications
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {string} [campaignId] Filter notifications by campaign ID
         * @param {NotificationsGetStatusEnum} [status] Filter notifications by status
         * @param {string} [deviceId] Filter notifications by device ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsGet(limit?: number, offset?: number, campaignId?: string, status?: NotificationsGetStatusEnum, deviceId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationsGet(limit, offset, campaignId, status, deviceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.notificationsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 * @export
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get list of notifications
         * @param {number} [limit] Maximum number of items to return
         * @param {number} [offset] Number of items to skip before starting to collect the result set
         * @param {string} [campaignId] Filter notifications by campaign ID
         * @param {NotificationsGetStatusEnum} [status] Filter notifications by status
         * @param {string} [deviceId] Filter notifications by device ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsGet(limit?: number, offset?: number, campaignId?: string, status?: NotificationsGetStatusEnum, deviceId?: string, options?: RawAxiosRequestConfig): AxiosPromise<NotificationsGet200Response> {
            return localVarFp.notificationsGet(limit, offset, campaignId, status, deviceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 * @export
 * @class NotificationsApi
 * @extends {BaseAPI}
 */
export class NotificationsApi extends BaseAPI {
    /**
     * 
     * @summary Get list of notifications
     * @param {number} [limit] Maximum number of items to return
     * @param {number} [offset] Number of items to skip before starting to collect the result set
     * @param {string} [campaignId] Filter notifications by campaign ID
     * @param {NotificationsGetStatusEnum} [status] Filter notifications by status
     * @param {string} [deviceId] Filter notifications by device ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationsGet(limit?: number, offset?: number, campaignId?: string, status?: NotificationsGetStatusEnum, deviceId?: string, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).notificationsGet(limit, offset, campaignId, status, deviceId, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const NotificationsGetStatusEnum = {
    New: 'new',
    Sent: 'sent',
    Failed: 'failed',
    Delivered: 'delivered',
    Undelivered: 'undelivered'
} as const;
export type NotificationsGetStatusEnum = typeof NotificationsGetStatusEnum[keyof typeof NotificationsGetStatusEnum];


